services:
  next-app:
    image: ghcr.io/bauloup1999/next-cda241/next-app:latest
    container_name: next-app-prod
    environment:
      - NODE_ENV=production
    ports:
      - "80:3000"
    restart: unless-stopped

networks:
  webnet:
    driver: bridge
