name: CI/CD Docker (Test & Prod)

on:
  push:
    branches:
      - develop
      - master

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build et publication de l’image Docker
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configurer QEMU (optionnel)
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2

      - name: Configurer Docker Buildx (optionnel)
        uses: docker/setup-buildx-action@v2

      - name: Connexion au registre GitHub Container
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Construire et pousser l’image Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/bauloup1999/next-cda241/next-app:latest

      - name: Vérifier l’image poussée
        run: |
          echo "Tags disponibles pour ghcr.io/bauloup1999/next-cda241/next-app"
          curl -H "Authorization: Bearer ${{ secrets.GHCR_PAT }}" \
               -s https://ghcr.io/v2/bauloup1999/next-cda241/next-app/tags/list | jq .

  deploy-test:
    name: Déploiement Test (port 8080)
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Déployer sur le serveur de test via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # 1. Aller dans le dossier de l’application
            cd /home/${{ secrets.SSH_USER }}/next-cda241

            # 2. Mettre à jour le dépôt local sur la branche develop
            git fetch origin
            git checkout develop
            git pull origin develop

            # 3. Authentification GHCR pour pull de l’image privée
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u bauloup1999 --password-stdin

            # 4a. Arrêter et supprimer tout conteneur écoutant sur le port 8080
            docker ps -q --filter "publish=8080" | xargs -r docker stop
            docker ps -aq --filter "publish=8080" | xargs -r docker rm

            # 4b. Descendre l’ancienne stack de test, y compris orphelins
            docker-compose -f docker-compose.dev.yml down --remove-orphans

            # 4c. Pull de l’image (tag latest)
            docker-compose -f docker-compose.dev.yml pull

            # 4d. (Re)création de la stack de test sur le port 8080
            docker-compose -f docker-compose.dev.yml up -d

  deploy-prod:
    name: Déploiement Prod (port 80)
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Déployer sur le serveur de prod via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # 1. Aller dans le dossier de l’application
            cd /home/${{ secrets.SSH_USER }}/next-cda241

            # 2. Mettre à jour le dépôt local sur la branche master
            git fetch origin
            git checkout master
            git pull origin master

            # 3. Authentification GHCR pour pull de l’image privée
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u bauloup1999 --password-stdin

            # 4a. Arrêter et supprimer tout conteneur écoutant sur le port 80
            docker ps -q --filter "publish=80" | xargs -r docker stop
            docker ps -aq --filter "publish=80" | xargs -r docker rm

            # 4b. Descendre l’ancienne stack de prod, y compris orphelins
            docker-compose -f docker-compose.prod.yml down --remove-orphans

            # 4c. Pull de l’image (tag latest)
            docker-compose -f docker-compose.prod.yml pull

            # 4d. (Re)création de la stack de prod sur le port 80
            docker-compose -f docker-compose.prod.yml up -d
