name: Build, publication et déploiement Docker

on:
  push:
    branches:
      - master   # ou "main" si votre branche principale s’appelle main

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Construire et publier l'image Docker
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configurer QEMU (optionnel)
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2

      - name: Configurer Docker Buildx (optionnel)
        uses: docker/setup-buildx-action@v2

      - name: Connexion au registre GitHub Container
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Construire et pousser l'image Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/bauloup1999/next-cda241/next-app:latest

      - name: Vérifier l'image poussée
        run: |
          echo "Tags disponibles pour ghcr.io/bauloup1999/next-cda241/next-app"
          curl -H "Authorization: Bearer ${{ secrets.GHCR_PAT }}" \
               -s https://ghcr.io/v2/bauloup1999/next-cda241/next-app/tags/list | jq .

  deploy:
    name: Déployer la stack via SSH
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Déployer sur le serveur via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # 1. Se placer dans le dossier de l'application
            cd /home/${{ secrets.SSH_USER }}/next-cda241

            # 2. Mettre à jour le dépôt Git (prérequis pour avoir docker-compose.prod.yml à jour)
            git pull origin master || git clone https://github.com/${{ github.repository_owner }}/next-cda241.git .

            # 3. Authentification GHCR pour pull d'une image privée
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u bauloup1999 --password-stdin

            # 4. Mettre à jour l'image et relancer la stack via docker-compose v1
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml up -d
