name: CI – build + tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build Next.js
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Installation des dépendances
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Upload du dossier .next
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next

  test:
    name: E2E tests Cypress
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Installation des dépendances
        run: npm ci

      - name: Télécharger l’artifact de build
        uses: actions/download-artifact@v3
        with:
          name: next-build
          path: ./

      - name: Démarrage du serveur Next.js (mode production)
        run: |
          nohup npm run start &
          npx wait-on http://localhost:3000
        env:
          NODE_ENV: production

      - name: Exécution des tests Cypress
        run: npx cypress run

      - name: Upload des vidéos Cypress
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
