name: CI – build + tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build Next.js
    runs-on: ubuntu-latest

    steps:
      # 1) On récupère le code
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      # 2) On installe Node.js v18
      - name: Setup Node.js (v18.x)
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # 3) On installe les dépendances
      - name: Installation des dépendances
        run: npm ci

      # 4) On build Next.js (génère .next/)
      - name: Build Next.js
        run: npm run build

      # 5) On uploade tout le dossier .next/ généré
      - name: Upload du dossier .next
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
          # NB : pas de wildcard “/**” ici, simplement “.next” suffit
          #     upload-artifact prendra par défaut tout le contenu du dossier .next/
          
  test:
    name: E2E tests Cypress
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 1) On récupère de nouveau le code (nécessaire pour exécuter Cypress,
      #    même si on aurait pu reporter l'extraction de .next/ seul, 
      #    mais c'est plus simple de repartir du checkout)
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      # 2) Node.js v18
      - name: Setup Node.js (v18.x)
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # 3) On réinstalle les dépendances
      - name: Installation des dépendances
        run: npm ci

      # 4) On télécharge l'artefact “next-build” (le .next/ généré précédemment)
      - name: Télécharger l’artifact de build
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: ./
          # => ceci va recréer le dossier “.next/” à la racine du workspace

      # 5) On démarre le serveur Next.js en production, en arrière-plan
      - name: Démarrage du serveur Next.js (mode production)
        run: |
          nohup npm run start &
          npx wait-on http://localhost:3000
        env:
          NODE_ENV: production

      # 6) On exécute les tests E2E avec Cypress
      - name: Exécution des tests Cypress
        run: npx cypress run

      # 7) (Optionnel) On uploade les vidéos Cypress
      - name: Upload des vidéos Cypress
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
