name: CI – build + tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build Next.js        # Identifiant 'build' (job id) --> 'needs: build' dans l'autre job fait référence à cet id
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Installation des dépendances
        run: npm ci

      - name: Build Next.js
        run: npm run build

      # ↑ Après 'npm run build', on doit UPLoADER exactement le dossier ".next" sous le nom d’artifact 'next-build'
      - name: Upload du dossier .next en artifact
        uses: actions/upload-artifact@v3   # ← bien @v3 ici
        with:
          name: next-build                 # ← le même nom que celui que l’on téléchargera ensuite
          path: .next                      

  test:
    name: E2E tests Cypress
    needs: build                         # ← on attend que 'build' soit terminé AVANT de lancer ce job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Installation des dépendances
        run: npm ci

      # ← TÉLÉCHARGE l’artifact 'next-build' UPLoADé par le job build
      - name: Télécharger l’artifact de build
        uses: actions/download-artifact@v3  # ← bien @v3 aussi
        with:
          name: next-build
          path: ./                           # on extrait dans le répertoire racine, donc on retrouvera ".next/"

      - name: Démarrage du serveur Next.js (mode production)
        run: |
          nohup npm run start &             # démarre 'next start' en background
          npx wait-on http://localhost:3000  # attend que le serveur soit disponible
        env:
          NODE_ENV: production

      - name: Exécution des tests Cypress
        run: npx cypress run

      - name: Upload des vidéos Cypress en tant qu’artifact
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
