name: CI – build + tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build Next.js
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du dépôt
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Installation de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # 3. Installation des dépendances
      - name: npm ci
        run: npm ci

      # 4. Build Next.js
      - name: Build Next.js
        run: npm run build

      # 5. Upload du dossier .next en tant qu'artifact
      - name: Upload du build (.next)
        uses: actions/upload-artifact@v2
        with:
          name: next-build
          path: .next

  test:
    name: E2E tests Cypress
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du dépôt
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Installation de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # 3. Installation des dépendances
      - name: npm ci
        run: npm ci

      # 4. Télécharger l’artifact next-build
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: next-build
          path: ./

      # 5. Démarrage du serveur Next.js (en production)
      - name: Start Next.js en prod
        run: |
          nohup npm run start &
          npx wait-on http://localhost:3000
        env:
          NODE_ENV: production

      # 6. Exécution des tests Cypress
      - name: Run Cypress
        run: npx cypress run

      # 7. Upload des vidéos Cypress
      - name: Upload des vidéos Cypress
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos
