name: CI – build + tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    name: Build et E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'   

      - name: Installation des dépendances
        run: npm ci

      - name: Build Next.js
        run: npm run build

    
      - name: Démarrage du serveur Next.js
        run: |
          nohup npm run start &        # lance 'next start' d'office (script défini dans package.json)
          npx wait-on http://localhost:3000  # attend que le serveur réponde sur le port 3000
        env:
          NODE_ENV: production

      - name: Exécution des tests Cypress
        run: npx cypress run
